config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 root to:"tweets#index"
 resources :tweets do
  resources :comments, only: :create
  get :asia,:namerica,:samerica,:africa,:europe,:oceania,:search,:runsearch,:tag,:stag, on: :collection
 end 
 resources :users, only: :show
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :risk
  belongs_to :day
  belongs_to :country
  belongs_to :user
  has_many   :comments, dependent: :destroy
  has_many :tweet_tag_relations, dependent: :destroy
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy

  validates :title, :block, :year, :month, :detail, presence: true
  validates :time, length: { maximum: 25 }
  validates :risk_id, :country_id, :day_id, numericality: { other_than: 1 }
  validates :month, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 12 }
  validates :year, format: { with: /\A([0-9]{4})+\z/ }
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :search_tweet, only: [:index, :runsearch]
  def index
    @tweet = Tweet.order('created_at DESC').page(params[:page]).per(25)
    @country = Country.where.not(id: 1)
  end

  def new
    @tweet = TweetsTag.new
  end

  def create
    @tweet = TweetsTag.new(tweets_params)
    if @tweet.valid?
      @tweet.save
      redirect_to root_path
    else

      render :new
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def edit
    @tweets = Tweet.find(params[:id])
  end

  def update
    @tweets = Tweet.find(params[:id])
    if @tweets.update(update_params)
      redirect_to tweet_path
    else
      render :edit
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])

    @tweet.destroy
    redirect_to root_path
  end

  def asia
    @tweet = Tweet.where(country_id: '195').or(Tweet.where(country_id: '4')).or(Tweet.where(country_id: '5')).or(Tweet.where(country_id: '11')).or(Tweet.where(country_id: '15'))
                  .or(Tweet.where(country_id: '16')).or(Tweet.where(country_id: '18')).or(Tweet.where(country_id: '19')).or(Tweet.where(country_id: '20')).or(Tweet.where(country_id: '21'))
                  .or(Tweet.where(country_id: '24')).or(Tweet.where(country_id: '35')).or(Tweet.where(country_id: '40')).or(Tweet.where(country_id: '41')).or(Tweet.where(country_id: '98'))
                  .or(Tweet.where(country_id: '46')).or(Tweet.where(country_id: '115')).or(Tweet.where(country_id: '50')).or(Tweet.where(country_id: '54')).or(Tweet.where(country_id: '56'))
                  .or(Tweet.where(country_id: '68')).or(Tweet.where(country_id: '76')).or(Tweet.where(country_id: '77')).or(Tweet.where(country_id: '78')).or(Tweet.where(country_id: '85'))
                  .or(Tweet.where(country_id: '97')).or(Tweet.where(country_id: '99')).or(Tweet.where(country_id: '104')).or(Tweet.where(country_id: '123')).or(Tweet.where(country_id: '125'))
                  .or(Tweet.where(country_id: '127')).or(Tweet.where(country_id: '129')).or(Tweet.where(country_id: '139')).or(Tweet.where(country_id: '140')).or(Tweet.where(country_id: '142'))
                  .or(Tweet.where(country_id: '144')).or(Tweet.where(country_id: '151')).or(Tweet.where(country_id: '149')).or(Tweet.where(country_id: '169')).or(Tweet.where(country_id: '173'))
                  .or(Tweet.where(country_id: '182')).or(Tweet.where(country_id: '184')).or(Tweet.where(country_id: '185')).order('created_at DESC').page(params[:page]).per(25)
  end

  def africa
    @tweet = Tweet.where(country_id: '8').or(Tweet.where(country_id: '12')).or(Tweet.where(country_id: '27')).or(Tweet.where(country_id: '29')).or(Tweet.where(country_id: '37'))
                  .or(Tweet.where(country_id: '38')).or(Tweet.where(country_id: '43')).or(Tweet.where(country_id: '44')).or(Tweet.where(country_id: '45')).or(Tweet.where(country_id: '48'))
                  .or(Tweet.where(country_id: '49').or(Tweet.where(country_id: '61'))).or(Tweet.where(country_id: '62')).or(Tweet.where(country_id: '64')).or(Tweet.where(country_id: '66'))
                  .or(Tweet.where(country_id: '67')).or(Tweet.where(country_id: '71')).or(Tweet.where(country_id: '71')).or(Tweet.where(country_id: '73')).or(Tweet.where(country_id: '74'))
                  .or(Tweet.where(country_id: '79')).or(Tweet.where(country_id: '82')).or(Tweet.where(country_id: '88')).or(Tweet.where(country_id: '89')).or(Tweet.where(country_id: '90'))
                  .or(Tweet.where(country_id: '95')).or(Tweet.where(country_id: '100')).or(Tweet.where(country_id: '102')).or(Tweet.where(country_id: '103')).or(Tweet.where(country_id: '105'))
                  .or(Tweet.where(country_id: '110')).or(Tweet.where(country_id: '117')).or(Tweet.where(country_id: '119')).or(Tweet.where(country_id: '122')).or(Tweet.where(country_id: '148'))
                  .or(Tweet.where(country_id: '150')).or(Tweet.where(country_id: '152')).or(Tweet.where(country_id: '160')).or(Tweet.where(country_id: '165')).or(Tweet.where(country_id: '166'))
                  .or(Tweet.where(country_id: '167')).or(Tweet.where(country_id: '171')).or(Tweet.where(country_id: '172')).or(Tweet.where(country_id: '175')).or(Tweet.where(country_id: '176'))
                  .or(Tweet.where(country_id: '177')).or(Tweet.where(country_id: '181')).or(Tweet.where(country_id: '188')).or(Tweet.where(country_id: '190')).or(Tweet.where(country_id: '193'))
                  .or(Tweet.where(country_id: '194')).order('created_at DESC').page(params[:page]).per(25)
  end

  def namerica
    @tweet = Tweet.where(country_id: '6').or(Tweet.where(country_id: '32')).or(Tweet.where(country_id: '42')).or(Tweet.where(country_id: '51')).or(Tweet.where(country_id: '55'))
                  .or(Tweet.where(country_id: '59')).or(Tweet.where(country_id: '63')).or(Tweet.where(country_id: '75')).or(Tweet.where(country_id: '92')).or(Tweet.where(country_id: '93'))
                  .or(Tweet.where(country_id: '94')).or(Tweet.where(country_id: '111')).or(Tweet.where(country_id: '112')).or(Tweet.where(country_id: '113')).or(Tweet.where(country_id: '121'))
                  .or(Tweet.where(country_id: '128')).or(Tweet.where(country_id: '131')).or(Tweet.where(country_id: '133')).or(Tweet.where(country_id: '137')).or(Tweet.where(country_id: '155'))
                  .or(Tweet.where(country_id: '163')).or(Tweet.where(country_id: '174')).order('created_at DESC').page(params[:page]).per(25)
  end

  def samerica
    @tweet = Tweet.where(country_id: '9').or(Tweet.where(country_id: '25')).or(Tweet.where(country_id: '26')).or(Tweet.where(country_id: '39')).or(Tweet.where(country_id: '65'))
                  .or(Tweet.where(country_id: '84')).or(Tweet.where(country_id: '106')).or(Tweet.where(country_id: '136')).or(Tweet.where(country_id: '145')).or(Tweet.where(country_id: '153'))
                  .or(Tweet.where(country_id: '156')).or(Tweet.where(country_id: '161')).order('created_at DESC').page(params[:page]).per(25)
  end

  def europe
    @tweet = Tweet.where(country_id: '2').or(Tweet.where(country_id: '3')).or(Tweet.where(country_id: '10')).or(Tweet.where(country_id: '14')).or(Tweet.where(country_id: '17'))
                  .or(Tweet.where(country_id: '58')).or(Tweet.where(country_id: '23')).or(Tweet.where(country_id: '28')).or(Tweet.where(country_id: '34')).or(Tweet.where(country_id: '36'))
                  .or(Tweet.where(country_id: '52')).or(Tweet.where(country_id: '60')).or(Tweet.where(country_id: '60')).or(Tweet.where(country_id: '72')).or(Tweet.where(country_id: '80'))
                  .or(Tweet.where(country_id: '81')).or(Tweet.where(country_id: '83')).or(Tweet.where(country_id: '86')).or(Tweet.where(country_id: '87')).or(Tweet.where(country_id: '91'))
                  .or(Tweet.where(country_id: '101')).or(Tweet.where(country_id: '108')).or(Tweet.where(country_id: '109')).or(Tweet.where(country_id: '126')).or(Tweet.where(country_id: '130'))
                  .or(Tweet.where(country_id: '138')).or(Tweet.where(country_id: '143')).or(Tweet.where(country_id: '146')).or(Tweet.where(country_id: '147')).or(Tweet.where(country_id: '154'))
                  .or(Tweet.where(country_id: '157')).or(Tweet.where(country_id: '158')).or(Tweet.where(country_id: '159')).or(Tweet.where(country_id: '162')).or(Tweet.where(country_id: '47'))
                  .or(Tweet.where(country_id: '168')).or(Tweet.where(country_id: '178')).or(Tweet.where(country_id: '180')).or(Tweet.where(country_id: '183')).or(Tweet.where(country_id: '186'))
                  .or(Tweet.where(country_id: '189')).or(Tweet.where(country_id: '187')).or(Tweet.where(country_id: '191')).or(Tweet.where(country_id: '192')).or(Tweet.where(country_id: '196'))
                  .order('created_at DESC').page(params[:page]).per(25)
  end

  def oceania
    @tweet = Tweet.where(country_id: '33').or(Tweet.where(country_id: '53')).or(Tweet.where(country_id: '57')).or(Tweet.where(country_id: '69')).or(Tweet.where(country_id: '120'))
                  .or(Tweet.where(country_id: '124')).or(Tweet.where(country_id: '132')).or(Tweet.where(country_id: '134')).or(Tweet.where(country_id: '135')).or(Tweet.where(country_id: '141'))
                  .or(Tweet.where(country_id: '164')).or(Tweet.where(country_id: '170')).order('created_at DESC').page(params[:page]).per(25)
  end

  def search
    return nil if params[:keyword] == ''

    tag = Tag.where(['name LIKE ?', "%#{params[:keyword]}%"])
    render json: { keyword: tag }
  end

  def runsearch
    @results = @p.result.order('created_at DESC')
  end

  def tag
    @tag = Tag.all.order('created_at DESC')
  end

  def stag
    @tag = Tag.find(params[:format])
    @tweets = @tag.tweets.order('created_at DESC')
  end

  private

  def tweets_params
    params.require(:tweets_tag).permit(:title, :risk_id, :country_id, :city, :block, :year, :month, :day_id, :time, :detail,
                                       :name).merge(user_id: current_user.id)
  end

  def update_params
    params.require(:tweet).permit(:title, :risk_id, :country_id, :city, :block, :year, :month, :day_id, :time, :detail,
                                  :name).merge(user_id: current_user.id)
  end

  def search_tweet
    @p = Tweet.ransack(params[:q])
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_all.html.erb
<% if @tweet.length !=0 %>
<div class="root">
   <%= link_to 'トップページへ戻る', root_path %>
</div>
  <% @tweet.each do |tweet| %>
 <li class='list'>


<div class="card text-dark bg-light mb-3" style="max-width: 180rem;">
  <div class="card-header">
    <a> <%= link_to  tweet_path(tweet.id) do %> <%= tweet.title %></a><%end%>
   </div>
  <div class="card-body">
    <h5 class="card-title"> <tr>
          <th class="detail-item">危険度</th>
          <td class="detail-value"><%= tweet.risk.name %></td> 
         </tr></h5>
    <p class="card-text">  <tr> 
          <th class="detail-item">国 ： </th>
          <td class="detail-value"><%= tweet.country.name %></td>
         </tr></p>
    <p class="card-text"> </tr>
           <th class="detail-item">内容</th>
           <td class="detail-value"><%= tweet.detail %></td>
         <tr></p>
        
    <p class="card-text">  <tr>
          <th class="detail-item">投稿者 ： 
             <a> <%= link_to  user_path(tweet.user.id) do %> <%=tweet.user.nickname %></a><%end%></th>
   
         </tr></p>
    <p class="card-text">    
            <%tweet.tags.each do |tag| %>
              <a> <%= link_to  stag_tweets_path(tag.id) do %>＃ <%= tag.name %></a><%end%>
            <%end%>
          </p>
  </div>
</div>

<%= paginate @tweet %>
       　　
  </li>
  <% end %>  
  <% else %>
  該当する投稿はありません
<% end %>
<br>
<%= link_to 'トップページへ戻る', root_path %>

app/views/tweets/_form.html.erb
 <% if @tweets.length !=0 %>
 <%= link_to 'トップページへ戻る', root_path %>
<% @tweets.each do |tweet| %>
 <li class='list'>
<div class="card text-dark bg-light mb-3" style="max-width: 180rem;">
  <div class="card-header">
  <%= tweet.title %>
             <a> <%= link_to  tweet_path (tweet.id)do %> 詳しくはこちら</a><%end%>  
             </div>
             <div class="card-body">
    <h5 class="card-title"> <tr>
          <th class="detail-item">国</th>
          <td class="detail-value"> <%= tweet.country.name %></td> 
         </tr></h5>

         <p class="card-text">  <tr> 
          <th class="detail-item">危険度 ： </th>
          <td class="detail-value">  <%= tweet.risk.name %></td>
         </tr></p>

           <p class="card-text"> <tr>
           <th class="detail-item">内容</th>
           <td class="detail-value"><%= tweet.detail %></td>
         </tr></p>
           <p class="card-text"> <tr>
            <%tweet.tags.each do |tag| %>
              <a> <%= link_to  stag_tweets_path(tag.id) do %>＃ <%= tag.name %></a><%end%>
            <%end%>
         </tr></p>
</div>

</div>
 </li>
        <%end%>

<% else %>
  該当する投稿はありません
<% end %>
<br>
<%= link_to 'トップページへ戻る', root_path %>

app/views/tweets/_map.html.erb
 <%# ここからGoogleAPI %>
       <div id="map"></div>

    <script>
        const mapEle = document.getElementById('map');

        function initialize() {
            var location = { lat: 35.658746, lng: 139.745465 }//東京タワー
            // 地図初期化
            var map = new google.maps.Map(mapEle, {
                zoom: 2,
                center: location
            });
        };
    </script>
    <script defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBBI4wIgWynv4jemfw_FpI4tNFpQbb74tU&callback=initialize"></script>

app/views/tweets/africa.html.erb
<div class="container">

 <h1> アフリカ</h1>

 <%= image_tag "africa.jpg", class:"left-image"%>
 <%= render "tweets/all" %>
</div>

app/views/tweets/asia.html.erb
<div class="container">

  <h1>アジア</h1>

    <%= image_tag "asia.jpg", class:"left-image"%>
  <%= render "tweets/all" %>

</div>

app/views/tweets/edit.html.erb
<div class="container">
<div class="items-sell-contents">
  <header class="items-sell-header">
  </header>

 <div class="items-sell-main">
    <h2 class="items-sell-title">あなたが体験した情報を入力</h2>

<%= form_with model:@tweets,  url: tweet_path, html: { method: :put },local: true do |f| %>

        <%= render 'shared/error_messages', model: f.object %>
<div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">タイトル　必須</label>
            <%= f.text_area :title,class:"form-control", id:"exampleFormControlTextarea1", rows:"3", placeholder:"例）笑顔で騙されかけました", maxlength:"40" %>
          </div>

          <div class="weight-bold-text">
             危険度
            <span class="indispensable">必須</span>
          </div>
            <%= f.collection_select(:risk_id, Risk.all, :id, :name, {}, {class:"select-box", id:"item-risk"}) %>
   </div>
     
     
     
        <div class="form">

          <div class="weight-bold-text">
            国
           <span class="indispensable">必須</span>
         </div>
            <%= f.collection_select(:country_id, Country.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>

         <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">地域　必須</label>
            <%= f.text_area :city,class:"form-control", id:"exampleFormControlTextarea1", rows:"3", placeholder:"例）アユタヤ付近" %>
         </div>

         <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">具体的な場所　必須</label>
            <%= f.text_area :block,class:"form-control", id:"exampleFormControlTextarea1", rows:"6", placeholder:"例）〇〇方面から△△方面に向かう途中の道（近くには□□があるところ！）", maxlength:"3000" %>
         </div>

         <div class="weight-bold-text">
            その体験した年
            <span class="indispensable">必須</span>
             <%= f.text_area :year, class:"form-control" ,type:"text", placeholder:"例)2021(半角)", aria_label:"default input example"%>
         </div>

         <div class="weight-bold-text">
            その体験した月
             <span class="indispensable">必須</span>
         </div>
            <%= f.text_area :month, class:"form-control" ,type:"text", placeholder:"例)9(半角)", aria_label:"default input example"%>

         <div class="weight-bold-text">
            その体験した時間帯
            <span class="indispensable">必須</span>
         </div>
            <%= f.collection_select(:day_id, Day.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>

         <div class="weight-bold-text">
            その体験した時間
            <%= f.text_area :time, class:"form-control" ,type:"text", placeholder:"例)現地時間の14時くらい。21:00.25字以内", aria_label:"default input example"%>
         </div>

         <div class="mb-3">
           <label for="exampleFormControlTextarea1" class="form-label">内容　必須</label>
           <%= f.text_area :detail,class:"form-control", id:"exampleFormControlTextarea1", rows:"9", placeholder:"例)＋＋が有名なレストランAに行こうとしていたところ、トゥクトゥクのお兄さんが話しかけてきた。「どこにくの？」と日本語で聞かれたので「レストランAに行きます」と答えたところ、「今日、レストランAはお休みだから水上マーケットに行こう」と言ってきた。私は怪しいと思いついて行かなかった。そしてレストランAに行ってみると普通に営業していた。", maxlength:"3000" %>
        </div>
       <div class="map_text">
        <h4>地図で確認してできるだけ鮮明に記述してください</h4>
        </div>
       <%= render "tweets/map" %>

      <div class="sell-btn-contents">
         <%= f.submit "変更する" ,class:"btn btn-outline-secondary" %>
         <%=link_to 'もどる', root_path, class:"btn btn-outline-primary" %>
      </div>
       <% end %>
  
</div>
</div>

app/views/tweets/europe.html.erb
<div class="container">

  <h1>ヨーロッパ</h1>

    <%= image_tag "europe.jpg", class:"left-image"%>
   <%= render "tweets/all" %>
</div>

app/views/tweets/new.html.erb
<div class="container">
  <div class="items-sell-contents">
    <header class="items-sell-header">
    </header>
 <div class="items-sell-main">
    <h2 class="items-sell-title">あなたが体験した情報を入力</h2>

<%= form_with model:@tweet,  url: tweets_path, html: { method: :post },local: true do |f| %>

        <%= render 'shared/error_messages', model: f.object %>
<div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">タイトル　必須</label>
            <%= f.text_area :title,class:"form-control", id:"exampleFormControlTextarea1", rows:"3", placeholder:"例）笑顔で騙されかけました", maxlength:"40" %>
          </div>

          <div class="weight-bold-text">
             危険度
            <span class="indispensable">必須</span>
          </div>
            <%= f.collection_select(:risk_id, Risk.all, :id, :name, {}, {class:"select-box", id:"item-risk"}) %>
   </div>
     
     
      
        <div class="form">
          <div class="weight-bold-text">
            国
           <span class="indispensable">必須</span>
         </div>
            <%= f.collection_select(:country_id, Country.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>

         <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">地域　必須</label>
            <%= f.text_area :city,class:"form-control", id:"exampleFormControlTextarea1", rows:"3", placeholder:"例）アユタヤ付近" %>
         </div>

         <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">具体的な場所　必須</label>
            <%= f.text_area :block,class:"form-control", id:"exampleFormControlTextarea1", rows:"6", placeholder:"例）〇〇方面から△△方面に向かう途中の道（近くには□□があるところ！）", maxlength:"3000" %>
         </div>

         <div class="weight-bold-text">
            その体験した年
            <span class="indispensable">必須</span>
         </div>
             <%= f.text_area :year, class:"form-control" ,type:"text", placeholder:"例)2021(半角)", aria_label:"default input example"%>

         <div class="weight-bold-text">
            その体験した月
             <span class="indispensable">必須</span>
         </div>
            <%= f.text_area :month, class:"form-control" ,type:"text", placeholder:"例)9(半角)", aria_label:"default input example"%>

         <div class="weight-bold-text">
            その体験した時間帯
            <span class="indispensable">必須</span>
         </div>
            <%= f.collection_select(:day_id, Day.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>

         <div class="weight-bold-text">
            その体験した時間
         </div>
            <%= f.text_area :time, class:"form-control" ,type:"text", placeholder:"例)現地時間の14時くらい。21:00.25字以内", aria_label:"default input example"%>

         <div class="mb-3">
           <label for="exampleFormControlTextarea1" class="form-label">内容　必須</label>
           <%= f.text_area :detail,class:"form-control", id:"exampleFormControlTextarea1", rows:"9", placeholder:"例)＋＋が有名なレストランAに行こうとしていたところ、トゥクトゥクのお兄さんが話しかけてきた。「どこにくの？」と日本語で聞かれたので「レストランAに行きます」と答えたところ、「今日、レストランAはお休みだから水上マーケットに行こう」と言ってきた。私は怪しいと思いついて行かなかった。そしてレストランAに行ってみると普通に営業していた。", maxlength:"3000" %>
        </div>
        
        <div class="weight-bold-text">
          タグ
         </div>
         <div class="tag-field", id='tag-field'>
            <%= f.text_field :name, class:"input-tag" %>
       </div>
        <div class="map_text">
        <h4>地図で確認してできるだけ鮮明に記述してください</h4>
        </div>
       <%= render "tweets/map" %>

      <div class="sell-btn-contents">
         <%= f.submit "投稿する" ,class:"btn  btn-outline-secondary" %>
         <%=link_to 'もどる', root_path, class:"btn btn-outline-primary" %>
      </div>
       <% end %>
   
    </div>


      
  </div>
</div>

app/views/tweets/oceania.html.erb
<div class="container">
 <h1>オセアニア</h1>
   <%= image_tag "oceania.jpg", class:"left-image"%>
  <%= render "tweets/all" %>
</div>

app/views/tweets/runsearch.html.erb
<div class="container">
<h3>
   検索結果
</h3>

<%# 検索結果の個数で条件分岐 %>
<% if @results.length !=0 %>
<%= link_to 'トップページへ戻る', root_path %>
  <% @results.each do |result| %>
    <li class='list'>
<div class="card text-dark bg-light mb-3" style="max-width: 180rem;">
  <div class="card-header">
    <%= result.title %>
          <a> <%= link_to  tweet_path (result.id)do %> 詳しくはこちら</a><%end%>
     </div>
      <div class="card-body">
   <h5 class="card-title"> <tr>
          <th class="detail-item">国 ： </th>
          <td class="detail-value"> <%= result.country.name %></td> 
         </tr></h5>
 <p class="card-text">  <tr> 
          <th class="detail-item">危険度 ： </th>
          <td class="detail-value">  <%= result.risk.name %></td>
         </tr></p>


  <p class="card-text">  <tr> 
          <td class="detail-value">  <%= result.year %></td>
          <th class="detail-item">年 </th>
         </tr></p>


        
          <p class="card-text">  <tr> 
          <th class="detail-item">内容 ： </th>
          <td class="detail-value">  <%= result.detail %></td>
         </tr></p>
          
            <p class="card-text">  <tr> 
          <th class="detail-item">時間帯 ： </th>
          <td class="detail-value">  <%= result.day.name %></td>
         </tr></p>
     
           <p class="card-text">  <tr> 
          <th class="detail-item">時間 ： </th>
          <td class="detail-value">  <%= result.time %></td>
         </tr></p>
          </div>
         </div>
          

     
     
       
    </li>
  <% end %>
<% else %>
  該当する投稿はありません
<% end %>
<br>
<%= link_to 'トップページへ戻る', root_path %>
</div>

app/views/tweets/samerica.html.erb
<div class="container">
 <h1>南アメリカ</h1>
 <%= image_tag "samerica.jpg", class:"left-image"%>
  <%= render "tweets/all" %>
</div>

app/views/tweets/show.html.erb
<div class="container">
<div class="item-show">
 <div class="card text-dark bg-light mb-3" style="max-width: 6000rem;">
  <div class="card-header">
      <h2><%= @tweet.title %></h2>
    </div>

    <div class="card-body">
       <h5 class="card-title"> <tr>
       <span>危険度</span>
        <%= @tweet.risk.name %>
       </tr></h5>
       <h5 class="card-title"> <tr>
        <span>国名</span>
        <%= @tweet.country.name %>
   <tr></p>
        <h5 class="card-title"> <tr>
        <span>地域 ： </span>
        <%= @tweet.city %>
   <tr></p>
    <h5 class="card-title"> <tr>
        <span>具体的な場所 ： </span>
        <%= @tweet.block %>
    <tr></p>
        <h5 class="card-title"> <tr>
        <%= @tweet.year %>
        <span>年</span>
<tr></p>
        <h5 class="card-title"> <tr>
        <%= @tweet.month %>
        <span>月</span>
 <tr></p>
      <h5 class="card-title"> <tr>
        <span>時間帯</span>
        <%= @tweet.day.name %>
      <tr></p>
       <h5 class="card-title"> <tr>
        <span>時間</span>
        <%= @tweet.time %>
      <tr></p>
      <h5 class="card-title"> <tr>
        <span>内容 : </span>
        <%= @tweet.detail %>
     <tr></p>
     </div>
     <%if user_signed_in?%>
        <%if current_user.id == @tweet.user_id %>
          <%= link_to  "投稿の編集", edit_tweet_path(@tweet.id), method: :get, class: "btn btn-outline-primary" %>
        
          <%= link_to "削除",  tweet_path(@tweet.id), method: :delete, class:"btn btn-outline-danger" %>
        <%end%>
        </div>
          <div class="card text-dark bg-light mb-3" style="max-width: 6000rem;">
  <div class="card-header">
   <h4>コメントフォーム</h4>
  </div>
        
         <%= form_with(model: [@tweet, @comment], local: true) do |form| %>
         <h5 class="card-title"> <tr>
        <%= form.text_area :text,  class:"form-control",placeholder: "コメントする", rows: "3" %>
        <%= form.submit "SEND" , class:"btn btn-outline-danger"%>
         <tr></p>
         <%end%>
      <%end%>
    </div>
    <div class="card text-dark bg-light mb-3" style="max-width: 6000rem;">
  <div class="card-header">
      <h4>＜コメント一覧＞</h4>
        <h5 class="card-title"> <tr>
      <% if @comments.length !=0 %>
      </div>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
       <% else %>
  <a>該当するコメントはありません<>
<% end %>
 <tr></p>
    </div>
 <%= render "tweets/map" %>
      </div>
  <div class="sell-btn-contents">
        
         <%=link_to 'もどる', root_path, class:"btn btn-outline-primary" %>
      </div>
    
   </div>
 </div>
</div>
 </div>

app/views/tweets/stag.html.erb
<div class="container">
<h3>#
<%=@tag.name%>
</h3>
  <%= render "tweets/form" %>
</div>

app/views/tweets/tag.html.erb
<div class="container">
<h1>タグ一覧</h1>
<% @tag.each do |tag| %>
<div>
 <a> <%= link_to  stag_tweets_path(tag.id) do %>＃ <%= tag.name %></a><%end%>
</div>
<%end%>
</div>