config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 root to:"tweets#index"
 resources :tweets do
  resources :comments, only: :create
  get :asia,:namerica,:samerica,:africa,:europe,:oceania,:search,:runsearch,:tag,:stag, on: :collection
 end 
 resources :users, only: :show
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link ral="stylesheet" href="style.css">
    
    <title>Before</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
     <header class="blog-header py-3">
      <% if user_signed_in? %>
      <div class="row flex-nowrap justify-content-between align-items-center">
        　 <div class="col-4 pt-1">
         <%= link_to "マイページ", "/users/#{current_user.id}" %>
        　 </div>
           <div class="col-4 text-center">
              <a><%= link_to '投稿する',  new_tweet_path, class: "btn btn-sm btn-outline-secondary" %></a> 
            </div>
           
            
            <div class="col-4 d-flex justify-content-end align-items-center">
             　
               <a><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-sm btn-outline-secondary" %></a> 
            </div>
        </div>
          <%else%>
       <div class="row flex-nowrap justify-content-between align-items-center">
        　 <div class="col-4 pt-1">
           <a><%= link_to '新規登録',  new_user_registration_path, class: "btn btn-sm btn-outline-secondary"%> </a> 
        　 </div>
           <div class="col-4 text-center">
             <a class="blog-header-logo text-dark"></a>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
             　 <a class="link-secondary" href="#" aria-label="Search">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
              　</a>
               <a><%= link_to 'ログイン', new_user_session_path, class: "btn btn-sm btn-outline-secondary" %></a> 
            </div>
        </div>
         <%end%>
    

     </header>
   </div>
  <nav class="container d-flex flex-column flex-md-row justify-content-between">
   <%= link_to '全世界', root_path%>
   <%= link_to "アジア", asia_tweets_path%>
   <%= link_to "アフリカ", africa_tweets_path%>
   <%= link_to "ヨーロッパ", europe_tweets_path%>
   <%= link_to "北アメリカ", namerica_tweets_path%>
   <%= link_to "南アメリカ", samerica_tweets_path%>
   <%= link_to "オセアニア", oceania_tweets_path%>
  </nav>
  
    <script defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBBI4wIgWynv4jemfw_FpI4tNFpQbb74tU&callback=initialize"></script>
   <script src="map.js"> </script>
   <%= yield %>
    
  </body>
</html>